image: node:18.18.2-bookworm

stages:
  - check
  - bump
  - build

check:
  stage: check
  image: node:18.18.2-bookworm
  script:
    - apt update && apt install libpangocairo-1.0-0 -y && apt autoclean && apt autoremove -y && rm -rf /var/lib/apt/lists/*
    - yarn install --frozen-lockfile && yarn lint
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "development"
      when: never
  when: always

bump:
  stage: bump
  image: node:18.18.2-bookworm
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn semantic-release
  when: always
  rules:
    - if: $CI_COMMIT_REF_NAME != "development"
      when: never

build:latest:
  stage: build
  image: electronuserland/builder:18-wine-07.23
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
  tags:
    - docker
  when: manual

build:deploy-tag:
  stage: build
  image: electronuserland/builder:18-wine-07.23
  script:
    - yarn install --frozen-lockfile
    - yarn build-publish
  artifacts:
    paths:
      - dist/
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(?:\d+.){2}(?:\d+)$/ && $CI_COMMIT_REF_NAME == "master"
  when: manual
