image: node:18-alpine

stages:
  - check
  - build

check:
  stage: check
  image: node:18-alpine
  script:
    - yarn install --frozen-lockfile
    - yarn lint
  tags:
    - docker

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
  tags:
    - docker
  only:
    refs:
      - development
      - master
