image: node:18.17.1-bookworm

stages:
  - check
  - bump
  - build

check:
  stage: check
  image: node:18.17.1-bookworm
  script:
    - apt update && apt install libpangocairo-1.0-0 -y && apt autoclean && apt autoremove -y && rm -rf /var/lib/apt/lists/*
    - yarn install --frozen-lockfile && yarn lint
  tags:
    - docker

build:latest:
  stage: build
  image: electronuserland/builder:18-wine-07.23
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
  tags:
    - docker
  when: manual

build:deploy:
  stage: build
  image: git
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - yarn version --minor
    - git add --all
    - git commit -m "Bump version"
    - git push origin master
  artifacts:
    paths:
      - dist/
  tags:
    - docker
  # only:
  #   refs:
  #     - master
  when: manual
