image: node:18.17.1-bookworm

stages:
  - check
  - build

check:
  stage: check
  image: node:18.17.1-bookworm
  script:
    - apt update && apt install libpangocairo-1.0-0 -y && apt autoclean && apt autoremove -y && rm -rf /var/lib/apt/lists/*
    - yarn install --frozen-lockfile && yarn lint
  tags:
    - docker

build:latest:
  stage: build
  image: electronuserland/builder:wine
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
  tags:
    - docker
  # only:
  #   refs:
  #     - development
  #     - master
  when: manual

build:tag:
  stage: build
  image: electronuserland/builder:wine
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    paths:
      - dist/
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(?:\d+.){2}(?:\d+)$/
      when: always
