image: node:20.15.1-bookworm

stages:
  - check
  - bump
  - build

check:
  stage: check
  image: node:20.15.1-bookworm
  script:
    - apt update && apt install libpangocairo-1.0-0 -y && apt autoclean && apt autoremove -y && rm -rf /var/lib/apt/lists/*
    - yarn install --frozen-lockfile && yarn lint
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "development"
      when: never
  when: always

bump:
  stage: bump
  image: node:20.15.1-bookworm
  before_script:
    - yarn install --frozen-lockfile
  script:
    - yarn semantic-release
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"

build:latest:
  stage: build
  image: electronuserland/builder:20-wine-07.24
  script:
    - yarn install --frozen-lockfile --ignore-engines
    - yarn build
  artifacts:
    expire_in: 3 months
    paths:
      - dist/
  tags:
    - docker
  when: manual

build:deploy-tag-all:
  stage: build
  image: electronuserland/builder:20-wine-07.24
  script:
    - yarn install --frozen-lockfile --ignore-engines
    - yarn build-publish
  artifacts:
    expire_in: 3 months
    paths:
      - dist/
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(?:\d+.){2}(?:\d+)$/
  when: manual

build:deploy-tag-linux:
  stage: build
  image: electronuserland/builder:20-wine-07.24
  script:
    - yarn install --frozen-lockfile --ignore-engines
    - yarn build-publish-linux
  artifacts:
    expire_in: 3 months
    paths:
      - dist/
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(?:\d+.){2}(?:\d+)$/
  when: manual

build:deploy-tag-windows:
  stage: build
  image: electronuserland/builder:20-wine-07.24
  script:
    - yarn install --frozen-lockfile --ignore-engines
    - yarn build-publish-windows
  artifacts:
    expire_in: 3 months
    paths:
      - dist/
  tags:
    - docker
  rules:
    - if: $CI_COMMIT_TAG =~ /^v(?:\d+.){2}(?:\d+)$/
  when: manual
