set NEXT_PUBLIC_PARSE_URL=***REMOVED***
set NEXT_PUBLIC_PARSE_APP_ID=***REMOVED***
set NEXT_PUBLIC_PARSE_JAVASCRIPT_KEY=***REMOVED***
set NEXT_PUBLIC_PARSE_USERNAME=stele
set NEXT_PUBLIC_PARSE_PASSWORD=***REMOVED***
set AWS_ACCESS_KEY_ID=***REMOVED***
set AWS_SECRET_ACCESS_KEY=***REMOVED***
set AWS_ENDPOINT_URL=***REMOVED***
set AWS_BUCKET_NAME=stele-updates
set IS_WINDOWS=true
set NEXT_PUBLIC_POLITICS_SERVICE_URL=***REMOVED***

start /d %LOCALAPPDATA%\Programs\digital-signage DigitalSignage.exe
